In [1]:
import pandas as pd
import regex as re
messages =pd.read_csv('SMSSpamCollection.txt', sep='\t',names=["label", "message" ])

In [2]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
messages.shape

(5572, 2)

In [4]:
import nltk
from nltk.stem import PorterStemmer#for stemming
from nltk.corpus import stopwords
stemm=PorterStemmer()

In [5]:
new_sentences=[]
for i in range(len(messages["message"])):
    temp=re.sub('[^a-zA-z]',' ',messages["message"][i])
    temp=temp.lower()
    temp=temp.split(" ")
    temp=[stemm.stem(i) for i in temp if i not in stopwords.words("english")]
    temp=" ".join(temp)
    new_sentences.append(temp)

In [6]:
new_sentences

['go jurong point  crazi   avail bugi n great world la e buffet    cine got amor wat   ',
 'ok lar    joke wif u oni   ',
 'free entri   wkli comp win fa cup final tkt   st may       text fa       receiv entri question std txt rate c appli             ',
 'u dun say earli hor    u c alreadi say   ',
 'nah think goe usf  live around though',
 'freemsg hey darl   week word back  like fun still  tb ok  xxx std chg send        rcv',
 'even brother like speak  treat like aid patent ',
 'per request  mell mell  oru minnaminungint nurungu vettam   set callertun caller  press    copi friend callertun',
 'winner   valu network custom select receivea      prize reward  claim call              claim code kl     valid    hour ',
 'mobil    month  u r entitl updat latest colour mobil camera free  call mobil updat co free            ',
 'gonna home soon want talk stuff anymor tonight  k  cri enough today ',
 'six chanc win cash             pound txt  csh   send        cost    p day   day      tsandc

In [7]:
if("until" in stopwords.words("english")):
    print(2)

2


# just checking the accuracy from using some other model like naivebayes using TF-IDF

In [8]:

from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer (max_features=3000)
x = tv.fit_transform(new_sentences).toarray()

In [9]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
y=pd.get_dummies(messages['label'],dtype=int)

In [11]:
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [12]:
y=y["spam"]


In [13]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [16]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [18]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [19]:
accuracy_score(y_test,y_pred)

0.8618814573137574

# word2vec

In [20]:
import gensim

In [21]:
new_sentences=[i.split(" ") for i in new_sentences]

In [22]:
r=new_sentences[0][3]

In [23]:
r

''

In [24]:
new_sentences = [[word for word in sentence if word != r] for sentence in new_sentences]


In [25]:
new_sentences

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'u', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'c',
  'appli'],
 ['u', 'dun', 'say', 'earli', 'hor', 'u', 'c', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select'

In [26]:
model=gensim.models.Word2Vec(new_sentences,min_count=2,)

In [ ]:
model.wv.similar_by_word("sleep")

In [27]:
model.wv["sleep"]

array([-0.19182321,  0.2971158 ,  0.06142031,  0.01446467,  0.04562692,
       -0.5608279 ,  0.16313976,  0.7187402 , -0.20682278, -0.13194424,
       -0.25226808, -0.5025479 , -0.11510804,  0.14646584,  0.11146039,
       -0.317493  ,  0.03306793, -0.37509763, -0.04090907, -0.67135906,
        0.2319824 ,  0.20515335,  0.10484251, -0.14632994, -0.1570997 ,
       -0.04356759, -0.30474   , -0.26570612, -0.33241773,  0.06584957,
        0.3403219 ,  0.04235097,  0.12945716, -0.2935746 , -0.13266852,
        0.35868493,  0.04422372, -0.28714836, -0.22627223, -0.7853967 ,
        0.08200774, -0.2741748 , -0.14884411,  0.00604748,  0.17816964,
       -0.08192895, -0.313022  ,  0.13150957,  0.29886323,  0.248017  ,
        0.20630927, -0.2851913 ,  0.03044896, -0.05397149, -0.16002089,
        0.14141735,  0.26361752, -0.07601591, -0.44707346,  0.23230183,
        0.08467354,  0.21780282, -0.06583047, -0.08747527, -0.48997125,
        0.29731753,  0.22894703,  0.27088657, -0.492528  ,  0.37

# building average word2vector

In [28]:
new_final=[]
for i in new_sentences:
    new_final.append(np.mean([model.wv[word] for word in i if word in model.wv.index_to_key],axis=0))

/Users/m.udarshreddy/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/m.udarshreddy/anaconda3/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [29]:
model.wv.key_to_index

{'u': 0,
 'call': 1,
 'go': 2,
 'get': 3,
 'ur': 4,
 'gt': 5,
 'lt': 6,
 'come': 7,
 'ok': 8,
 'day': 9,
 'free': 10,
 'know': 11,
 'love': 12,
 'like': 13,
 'time': 14,
 'good': 15,
 'want': 16,
 'got': 17,
 'text': 18,
 'send': 19,
 'txt': 20,
 'need': 21,
 'p': 22,
 'one': 23,
 'today': 24,
 'n': 25,
 'take': 26,
 'see': 27,
 'stop': 28,
 'r': 29,
 'home': 30,
 'think': 31,
 'repli': 32,
 'lor': 33,
 'sorri': 34,
 'k': 35,
 'tell': 36,
 'still': 37,
 'mobil': 38,
 'back': 39,
 'da': 40,
 'dont': 41,
 'make': 42,
 'phone': 43,
 'week': 44,
 'pleas': 45,
 'say': 46,
 'hi': 47,
 'new': 48,
 'work': 49,
 'pl': 50,
 'later': 51,
 'hope': 52,
 'miss': 53,
 'ask': 54,
 'co': 55,
 'msg': 56,
 'min': 57,
 'meet': 58,
 'c': 59,
 'dear': 60,
 'messag': 61,
 'night': 62,
 'wait': 63,
 'happi': 64,
 'well': 65,
 'give': 66,
 'thing': 67,
 'tri': 68,
 'much': 69,
 'great': 70,
 'oh': 71,
 'claim': 72,
 'wat': 73,
 'hey': 74,
 'number': 75,
 'b': 76,
 'thank': 77,
 'friend': 78,
 'way': 79,
 'ye':

In [30]:
X_train[17]

array([0., 0., 0., ..., 0., 0., 0.])

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_final, y, test_size=0.33, random_state=42)

In [35]:
import numpy as np

# Find the indexes with NaN values
nan_indexes = []
for i in range(len(X_train)):
    if np.isnan(X_train[i]).any():
        nan_indexes.append(i)

nan_indexes

[17, 127, 166, 246, 830, 1061, 1270, 1751, 2692, 3120, 3472, 3475, 3710]

In [36]:
for indx in sorted(nan_indexes, reverse=True):
    if indx < len(X_train):
        del X_train[indx]


In [37]:
for indx in nan_indexes:

   # checking whether the corresponding iterator index is less than the list length
   if indx < len(y_train):

      # removing element by index using del keyword
      del y_train[indx]


In [38]:
len(y_train)

3720

In [407]:
 X_train=[l.tolist() for l in X_train]

In [76]:
X_test=[l.tolist() for l in X_test]

In [32]:
y_train=y_train.tolist()

In [33]:
y_test=y_test.tolist()

In [116]:
import numpy as np

# Find the indexes with NaN values
nan_indexes2 = []
for i in range(len(X_test)):
    if np.isnan(X_test[i]).any():
        nan_indexes2.append(i)

nan_indexes2

[]

In [117]:
for indx in nan_indexes2:

   # checking whether the corresponding iterator index is less than the list length
   if indx < len(X_test):

      # removing element by index using del keyword
      del X_test[indx]


In [118]:
for indx in nan_indexes2:

   # checking whether the corresponding iterator index is less than the list length
   if indx < len(y_test):

      # removing element by index using del keyword
      del y_test[indx]


In [267]:
nan_indexes

[17, 127, 166, 246, 830, 1061, 1270, 1751, 2692, 3120, 3472, 3475, 3710]

In [42]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [274]:
X_train1=X_train[19:281]

In [275]:
y_train1=y_train[19:281]

In [71]:
for i in range(len(X_test)):
    if np.isnan(X_train[i]).any():
        print(i)
   

In [120]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [121]:
accuracy_score(y_test,y_pred)

0.5155210643015521

In [123]:
len(X_train)

3720